# -*- coding: utf-8 -*-
"""Hog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-gwe9eOp8gxG2Aaa1RyyNbMv_fwOLgh
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt

from skimage.feature import hog
from skimage import exposure

# %matplotlib inline

train_images=[]
for directory_path in glob.glob(r"D:\DP\Single_fifteen\Train"):
  for img_path in glob.glob(os.path.join(directory_path,"*tiff")):
    #print(img_path)
    img=cv2.imread(img_path,cv2.IMREAD_COLOR)
    
    img=cv2.resize(img, (256,256))
    img=cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    train_images.append(img)

for i in train_images:
  fd, hog_image = hog(image[i], orientations=15, pixels_per_cell=(20, 20),
                    cells_per_block=(2, 2), visualize=True, block_norm="L1", transform_sqrt=False)
# display the image
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4), sharex=True, sharey=True)

ax1.axis('off')
ax1.imshow(image, cmap=plt.cm.gray)
ax1.set_title('Input image')

# Rescale histogram for better display
hog_image_rescaled = exposure.rescale_intensity(hog_image, in_range=(0, 10))
# display the HOG features
ax2.axis('off')
ax2.imshow(hog_image_rescaled, cmap=plt.cm.gray)
ax2.set_title('Histogram of Oriented Gradients')