# -*- coding: utf-8 -*-
"""LBP_new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HCjed7HD7sFqCH9U9lwHsEIycNiUwgGs
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
   
      
def get_pixel(img, center, x, y):
      
    new_value = 0
      
    try:
       
        if img[x][y] >= center:
            new_value = 1
              
    except:
        
        pass
      
    return new_value
   
# Function for calculating LBP
def lbp_calculated_pixel(img, x, y):
   
    center = img[x][y]
   
    val_ar = []
      
   
    val_ar.append(get_pixel(img, center, x-1, y-1))
      
   
    val_ar.append(get_pixel(img, center, x-1, y))
      
   
    val_ar.append(get_pixel(img, center, x-1, y + 1))
      
   
    val_ar.append(get_pixel(img, center, x, y + 1))
      
    
    val_ar.append(get_pixel(img, center, x + 1, y + 1))
      
   
    val_ar.append(get_pixel(img, center, x + 1, y))
      
   
    val_ar.append(get_pixel(img, center, x + 1, y-1))
      
   
    val_ar.append(get_pixel(img, center, x, y-1))
       
    
    power_val = [1, 2, 4, 8, 16, 32, 64, 128]
   
    val = 0
      
    for i in range(len(val_ar)):
        val += val_ar[i] * power_val[i]
          
    return val
 

img_bgr=[]
for directory_path in glob.glob(r"D:\DP\Single_fifteen\Train"):
  for img_path in glob.glob(os.path.join(directory_path,"*tiff")):
    #print(img_path)
    img=cv2.imread(img_path,cv2.IMREAD_COLOR)
    
    img=cv2.resize(img, (256,256))
    img=cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    train_images.append(img)  
for i in img_bgr: 
height, width, _ = img_bgr[i].shape
  
img_gray = cv2.cvtColor(img_bgr[i],
                        cv2.COLOR_BGR2GRAY)
  
img_lbp = np.zeros((height, width),
                   np.uint8)
   
for i in range(0, height):
    for j in range(0, width):
        img_lbp[i, j] = lbp_calculated_pixel(img_gray, i, j)
  
plt.imshow(img_bgr[i])
plt.show()
   
plt.imshow(img_lbp[i], cmap ="gray")
plt.show()
   
print("LBP Program is finished")